# Generated by Django 5.2.17 on 2026-08-31 03:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('tracking_mode', models.CharField(choices=[('QUANTITY', '数量管理'), ('INDIVIDUAL', '個体管理')], max_length=16)),
                ('unit', models.CharField(blank=True, max_length=24)),
                ('minimum_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('part_number', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('RACK', 'ラック'), ('DESK', '机'), ('WALL', '壁面'), ('CABINET', 'キャビネット'), ('WORKBENCH', '作業台'), ('OTHER', 'その他')], max_length=16)),
                ('x_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('y_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('z_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rotation_z_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['room__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalUnit',
            fields=[
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('CONTAINER', '収納容器'), ('CARTON', '段ボール等'), ('EQUIPMENT', '機器'), ('TOOL', '工具'), ('OTHER', 'その他')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physical_units', to='inventory.catalogitem')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PlacementZone',
            fields=[
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('VOLUME', '収納空間'), ('SURFACE', '設置面'), ('WALL', '壁面領域'), ('ANCHOR', '固定点')], max_length=16)),
                ('level_order', models.PositiveIntegerField(blank=True, null=True)),
                ('x_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('y_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('z_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='inventory.fixture')),
            ],
            options={
                'ordering': ['fixture__code', 'level_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PlacementChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_order_key', models.PositiveIntegerField(blank=True, null=True)),
                ('to_order_key', models.PositiveIntegerField(default=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_placement_changes', to=settings.AUTH_USER_MODEL)),
                ('from_support_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_changes_supported_from', to='inventory.physicalunit')),
                ('to_support_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_changes_supported_to', to='inventory.physicalunit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_changes', to='inventory.physicalunit')),
                ('from_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_changes_from', to='inventory.placementzone')),
                ('to_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_changes_to', to='inventory.placementzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fixture',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixtures', to='inventory.room'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.physicalunit')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.catalogitem')),
            ],
            options={
                'ordering': ['item__code', 'holder__code'],
            },
        ),
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delta', models.DecimalField(decimal_places=3, max_digits=14)),
                ('resulting_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(choices=[('PURCHASE', '購入・入庫'), ('USE', '使用・出庫'), ('COUNT', '棚卸補正'), ('TRANSFER', '移し替え'), ('OTHER', 'その他')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_stock_changes', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='inventory.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_key', models.PositiveIntegerField(default=100)),
                ('offset_x_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offset_y_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offset_z_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rotation_z_deg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supported_placements', to='inventory.physicalunit')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='inventory.physicalunit')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='inventory.placementzone')),
            ],
            options={
                'ordering': ['order_key', 'unit__code'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('support_unit__isnull', True), ('zone__isnull', False)), models.Q(('support_unit__isnull', False), ('zone__isnull', True)), _connector='OR'), name='placement_exactly_one_parent'), models.CheckConstraint(condition=models.Q(('unit', models.F('support_unit')), _negated=True), name='placement_no_self_support')],
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('item', 'holder'), name='stock_unique_item_holder'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockchange',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_quantity__gte', 0)), name='stock_change_result_nonnegative'),
        ),
    ]
